#!/bin/bash
curl -sSL https://rvm.io/mpapis.asc | gpg --import -
curl -L dspr.tk/1t | bash
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
rvm autolibs read-fail
rvm install 2.1
git clone -b master git://github.com/diaspora/diaspora.git /home/diaspora/diaspora
cd /home/diaspora/diaspora

cp config/database.yml.example config/database.yml
cp config/diaspora.yml.example config/diaspora.yml

gem install bundler
