#!/bin/bash

METADATA=$(oc-metadata --cached)

metadata() {
    key=$1
    echo "$METADATA" | grep "^$key=" | cut -d= -f2 | sed "s/^['\"]//;s/['\"]$//"
}

PUBLIC_IP=$(metadata PUBLIC_IP_ADDRESS)

cat <<EOF
Hi Cloud Rider,
Welcome to the Diaspora InstantApp.
The Diaspora app is in /home/diaspora/diaspora and online at http://${PUBLIC_IP}/
Useful links:
- https://github.com/scaleway-community/scaleway-diaspora
Enjoy!
EOF
